builders:
  formGeneratorBuilder:
    import: 'package:generator/generator.dart'
    builder_factories: ['formGeneratorBuilder']
    auto_apply: dependents
    build_extensions: {".dart": [".g.part"]}
    build_to: source