// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code
// ignore_for_file: camel_case_types

import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:flutter_annotation_form_builder/teste/unFisier.dart';

class UnFisierFormWidget extends StatelessWidget {
  UnFisierFormWidget({
    Key? key,
    required this.unfisier,
  }) : super(key: key);

  final UnFisier unfisier;
  final _formKey = GlobalKey<FormBuilderState>();

  @override
  Widget build(BuildContext context) {
    return FormBuilder(
      key: _formKey,
      child: Column(children: [
        FormBuilderDateTimePicker(
          name: "b",
          inputType: InputType.time,
        ),
      ]),
    );
  }
}
